name: Vite build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VITE_USER_FETCH_LOCATION: "https://reqs.pubhalls.com"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        path: dist
